apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .ClusterManagerName }}-registration-webhook
  namespace: {{ .ClusterManagerNamespace }}
  labels:
    app: {{ .ClusterManagerName }}-registration-webhook
spec:
  replicas: {{ .Replica }}
  selector:
    matchLabels:
      app: {{ .ClusterManagerName }}-registration-webhook
  template:
    metadata:
      labels:
        app: {{ .ClusterManagerName }}-registration-webhook
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 70
            podAffinityTerm:
              topologyKey: failure-domain.beta.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .ClusterManagerName }}-registration-webhook
          - weight: 30
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .ClusterManagerName }}-registration-webhook
      {{ if not .HostedMode }}
      serviceAccountName: {{ .ClusterManagerName }}-registration-webhook-sa
      {{ end }}
      containers:
      - name: {{ .ClusterManagerName }}-webhook
        image: {{ .RegistrationImage }}
        args:
        - /registration
        - "webhook-server"
        - "port=9443"
        {{ if gt (len .RegistrationFeatureGates) 0 }}
        {{range .RegistrationFeatureGates}}
        - {{ . }}
        {{ end }}
        {{ else }}
        - "--feature-gates=DefaultClusterSet=true"
        {{ end }}
        {{ if .HostedMode }}
        - "--kubeconfig=/var/run/secrets/hub/kubeconfig"
        {{ end }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2m
            memory: 16Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTP
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            scheme: HTTP
            port: 8000
          initialDelaySeconds: 2
        ports:
        - containerPort: 9443
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-secret
          readOnly: true
        {{ if .HostedMode }}
        - mountPath: /var/run/secrets/hub
          name: kubeconfig
          readOnly: true
        {{ end }}
      volumes:
      - name: webhook-secret
        secret:
          secretName: registration-webhook-serving-cert
      {{ if .HostedMode }}
      - name: kubeconfig
        secret:
          secretName: {{ .ClusterManagerName }}-registration-webhook-sa-kubeconfig
      {{ end }}
