apiVersion: v1
data:
  agent-name: ${AGENT_NAME_ENCODED}
  cluster-name: ${SPOKE_CLUSTER_NAME_ENCODED}
  kubeconfig: ${HUB_KUBECONFIG_ENCODED}
kind: Secret
metadata:
  name: hub-kubeconfig-secret
  namespace: open-cluster-management-agent
type: Opaque