apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: managedclustervalidators.admission.cluster.open-cluster-management.io
webhooks:
- name: managedclustervalidators.admission.cluster.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: open-cluster-management-hub
      name: managedcluster-admission
      path: /validate-cluster-open-cluster-management-io-v1-managedcluster
      port: 9443
    caBundle: CA_PLACE_HOLDER
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - cluster.open-cluster-management.io
    apiVersions:
    - "*"
    resources:
    - managedclusters
  admissionReviewVersions: ["v1beta1","v1"]
  sideEffects: None
  timeoutSeconds: 3

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: managedclustermutators.admission.cluster.open-cluster-management.io
webhooks:
- name: managedclustermutators.admission.cluster.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: open-cluster-management-hub
      name: managedcluster-admission
      path: /mutate-cluster-open-cluster-management-io-v1-managedcluster
      port: 9443
    caBundle: CA_PLACE_HOLDER
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - cluster.open-cluster-management.io
    apiVersions:
    - "*"
    resources:
    - managedclusters
  admissionReviewVersions: ["v1beta1","v1"]
  sideEffects: None
  timeoutSeconds: 3

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: managedclustersetbindingvalidators.admission.cluster.open-cluster-management.io
webhooks:
- name: managedclustersetbindingvalidators.admission.cluster.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: open-cluster-management-hub
      name: managedcluster-admission
      path: /validate-cluster-open-cluster-management-io-v1beta1-managedclustersetbinding
      port: 9443
    caBundle: CA_PLACE_HOLDER
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - cluster.open-cluster-management.io
    apiVersions:
    - v1beta1
    resources:
    - managedclustersetbindings
  admissionReviewVersions: ["v1beta1","v1"]
  sideEffects: None
  timeoutSeconds: 3

---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: managedclustersetbindingv1beta2validators.admission.cluster.open-cluster-management.io
webhooks:
- name: managedclustersetbindingv1beta2validators.admission.cluster.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: open-cluster-management-hub
      name: managedcluster-admission
      path: /validate-cluster-open-cluster-management-io-v1beta2-managedclustersetbinding
      port: 9443
    caBundle: CA_PLACE_HOLDER  
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - cluster.open-cluster-management.io
    apiVersions:
    - v1beta2
    resources:
    - managedclustersetbindings
  admissionReviewVersions: ["v1beta1","v1"]
  sideEffects: None
  timeoutSeconds: 3
