coverage:
  status:
    patch: off # disable patch status, https://docs.codecov.com/docs/commit-status#patch-status
    project:
      default:
        target: auto
        threshold: 1%

ignore:
  - "**/*generated*.go"
  - "**/*_test.go"
  - "test/**"
  - "pkg/*/testing/**"
  - "pkg/work/spoke/spoketesting/**"
  - "pkg/work/hub/test/**"
  - "pkg/addon/templateagent/testmanifests/**"
  - "manifests/**"
  - "deploy/**"
