apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:work:agent:extension-apiserver
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:work:agent:extension-apiserver
subjects:
  - kind: ServiceAccount
    name: work-agent-sa
    namespace: open-cluster-management-agent