apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:{{ .ClusterManagerName }}-grpc-server
{{ if gt (len .Labels) 0 }}
  labels:
  {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
  {{ end }}
{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:{{ .ClusterManagerName }}-grpc-server
subjects:
- kind: ServiceAccount
  namespace: {{ .ClusterManagerNamespace }}
  name: grpc-server-sa
