apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-server-sa
  namespace: {{ .ClusterManagerNamespace }}
{{ if gt (len .Labels) 0 }}
  labels:
  {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
  {{ end }}
{{ end }}
