apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: klusterlet
spec:
  deployOption:
    mode: Default
  registrationImagePullSpec: quay.io/open-cluster-management/registration
  workImagePullSpec: quay.io/open-cluster-management/work
  clusterName: cluster1
  namespace: open-cluster-management-agent
  externalServerURLs:
  - url: https://localhost
  registrationConfiguration:
    featureGates:
    - feature: AddonManagement
      mode: Enable
    # Uncomment the following configuration lines to add hostAliases for hub api server, 
    # if the server field in your hub cluster kubeconfig is a domain name instead of an ipv4 address.
    # For example, https://xxx.yyy.zzz.
    # This configuration is used for registration-agent and work-agent to communicate with hub api server.
    # hubApiServerHostAlias:
    # ip: "1.2.3.4"
    # hostname: "xxx.yyy.zzz"
