# RoleBinding for registration mandatory permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:management:{{ .KlusterletName }}-registration:agent
  namespace: {{ .AgentNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:management:{{ .KlusterletName }}-registration:agent
subjects:
  - kind: ServiceAccount
    name: {{ .KlusterletName }}-registration-sa
    namespace: {{ .AgentNamespace }}
