# RoleBinding for work mandatory permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:management:{{ .KlusterletName }}-work:agent
  namespace: {{ .AgentNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:management:{{ .KlusterletName }}-work:agent
subjects:
  - kind: ServiceAccount
    name: {{ .KlusterletName }}-work-sa
    namespace: {{ .AgentNamespace }}
