apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc
    chart: grc-chart-2.7.0
    component: ocm-grc-sa
    release: grc
  name: grc-sa
