apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc
    chart: grc-chart-2.7.0
    component: ocm-grc-rolebinding
    release: grc
  name: grc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grc-role
subjects:
- kind: ServiceAccount
  name: grc-sa
