apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc
    chart: grc-chart-2.7.0
    component: ocm-grc-role
    release: grc
  name: grc-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
