apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grc-policy-propagator-deployment.yaml
- grc-policy-propagator-metrics-service.yaml
- grc-policy-propagator-role.yaml
- grc-policy-propagator-rolebinding.yaml
- grc-policy-propagator-serviceaccount.yaml

images:
- name: quay.io/open-cluster-management/governance-policy-propagator:latest
  newName: quay.io/morvencao/governance-policy-propagator
  newTag: latest
