apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  registrationImagePullSpec: quay.io/open-cluster-management/registration
  workImagePullSpec: quay.io/open-cluster-management/work
  placementImagePullSpec: quay.io/open-cluster-management/placement
  addOnManagerImagePullSpec: quay.io/open-cluster-management/addon-manager
  deployOption:
    mode: Default
  registrationConfiguration:
    featureGates:
    - feature: DefaultClusterSet
      mode: Enable
