apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluxcd-addon-manager
  namespace: fluxcd-addon
---
# cluster-admin is used here for simplicity, scope this down before using
# outside a demo/dev environment. See the Notes section in the README.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluxcd-addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: fluxcd-addon-manager
    namespace: fluxcd-addon
