apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: klusterlet
  namespace: {{ .AgentNamespace }}
spec:
  podSelector:
    matchLabels:
      app: klusterlet
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
  - to:
    - namespaceSelector:
        matchLabels:
          addon.open-cluster-management.io/namespace: "true"
    ports:
    - protocol: TCP
      port: 443
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    ports:
    - protocol: TCP
      port: 443
