apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: klusterlet-agent
  namespace: {{ .AgentNamespace }}
spec:
  podSelector:
    matchLabels:
      app: klusterlet-agent
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - ports:
    - protocol: TCP
      port: 443
  - ports:
    - protocol: TCP
      port: 9443
  - to:
    - podSelector: {}
