apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-subscription
  namespace: default
spec:
  channel: default/demo-helmrepo
  name: nginx-ingress
  placement:
    placementRef:
      name: demo-placement
      kind: Placement
  packageOverrides:
  - packageName: nginx-lego
    packageAlias: nginx-lego-simple
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 1
