apiVersion: v1
kind: ServiceAccount
metadata:
  name: registration-controller-sa
  namespace: {{ .ClusterManagerNamespace }}
  {{ if .ManagedClusterIdentityCreatorRole }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .ManagedClusterIdentityCreatorRole }}
  {{ else }}
  annotations:
    eks.amazonaws.com/role-arn-: ""
  {{end}}
  labels:
    {{ if gt (len .Labels) 0 }}
    {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
    {{ end }}
    {{ end }}
