kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocm-controlplane
  labels:
    app: ocm-controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocm-controlplane
  template:
    metadata:
      labels:
        app: ocm-controlplane
    spec:
      containers:
      - name: controlplane
        image: docker.io/yaoyuchen/controlplane:latest
        imagePullPolicy: Always
        args:
          - "/ocm-controlplane"
          - "--authorization-mode=RBAC"
          - "--feature-gates=DefaultClusterSet=true"
          - "--enable-bootstrap-token-auth"
          - "--service-account-key-file=/controlplane/cert/kube-serviceaccount.key"
          - "--client-ca-file=/controlplane/cert/client-ca.crt"
          - "--client-key-file=/controlplane/cert/client-ca.key"
          - "--enable-bootstrap-token-auth"
          - "--enable-priority-and-fairness=false"
          - "--api-audiences="    
          - "--storage-backend=etcd3"
          - "--v=1"
          - "--service-account-lookup=false"
          - "--service-account-signing-key-file=/controlplane/cert/kube-serviceaccount.key"
          - "--enable-admission-plugins=NamespaceLifecycle,ServiceAccount,MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
          - "--disable-admission-plugins=TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,PodSecurity,PersistentVolumeClaimResize,RuntimeClass,DefaultIngressClass"
          - "--bind-address=0.0.0.0"
          - "--secure-port=9443"
          - "--tls-cert-file=/controlplane/cert/serving-kube-apiserver.crt"
          - "--tls-private-key-file=/controlplane/cert/serving-kube-apiserver.key"
          - "--feature-gates=DefaultClusterSet=true"
          - "--enable-embedded-etcd=true"
          - "--service-cluster-ip-range=10.0.0.0/24"
          - "--service-account-issuer=https://kubernetes.default.svc"
          - "--external-hostname=API_HOST"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
        - name: controlplane-cert
          mountPath: /controlplane/cert
          readOnly: true
        - mountPath: /.ocmconfig
          name: ocmconfig 
      volumes:
      - name: controlplane-cert
        secret:
          secretName: controlplane-cert
      - name: ocmconfig 
        emptyDir:
          sizeLimit: 500Mi

