apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: demo-placement
  namespace: default
spec:
  numberOfClusters: 1
  clusterSets:
    - default
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            purpose: test
