
# Adds namespace to all resources.
namespace: open-cluster-management-hub

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: multicloud-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
#
# General rule here is anything deployed by OLM bundles should go here as well,
# this is used in "make deploy" for developers and should mimic what OLM deploys
# for you. CRDs are an exception to this as we don't want to have to list them all
# here. These are deployed via a "make install" dependency.

resources:
- ./clusterrole_binding.yaml
- ./clusterrole.yaml
- ./deployment.yaml
- ./service_account.yaml
- ./service.yaml
- ./webhook.yaml
- ../hub

images:
- name: quay.io/open-cluster-management/registration:latest
  newName: quay.io/open-cluster-management/registration
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# inject conversion webhook in clusterset crd
patches:
- path: managedclustersets_conversion_webhook.crd.yaml

# generate servering cert for webhook
secretGenerator:
- files:
  - cert/tls.crt
  - cert/tls.key
  name: registration-webhook-serving-cert
