# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedclustersets.cluster.open-cluster-management.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: open-cluster-management-hub
          name: managedcluster-admission
          path: /convert
          port: 9443
        caBundle: CA_PLACE_HOLDER
      conversionReviewVersions:
      - v1beta1
      - v1beta2
