apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  # Installed into flux-system (already created by the addon) so this demo
  # only needs one ManifestWork. If you want a different target namespace,
  # add it as its own object in an earlier ManifestWork first (see the Notes
  # section in the README).
  targetNamespace: flux-system
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
