apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grc
    component: ocm-policy-addon-ctrl
  name: grc-policy-addon-controller
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: grc
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
                      - arm64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: ocm-antiaffinity-selector
                      operator: In
                      values:
                        - grcpolicyaddon
                topologyKey: topology.kubernetes.io/zone
              weight: 70
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: ocm-antiaffinity-selector
                      operator: In
                      values:
                        - grcpolicyaddon
                topologyKey: kubernetes.io/hostname
              weight: 35
      containers:
        - args:
            - controller
          command:
            - governance-policy-addon-controller
            - "--controlplane"
            - "--hubkubeconfig=/var/run/secrets/hub/kubeconfig"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: CONFIG_POLICY_CONTROLLER_IMAGE
              value: quay.io/open-cluster-management/config-policy-controller:latest
            - name: KUBE_RBAC_PROXY_IMAGE
              value: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.10
            - name: GOVERNANCE_POLICY_FRAMEWORK_ADDON_IMAGE
              value: quay.io/open-cluster-management/governance-policy-framework-addon:latest
          image: quay.io/open-cluster-management/governance-policy-addon-controller:latest
          imagePullPolicy: Always
          name: manager
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/run/secrets/hub
              name: kubeconfig
              readOnly: true
      serviceAccountName: policy-sa
      volumes:
        - emptyDir: {}
          name: tmp
        - name: kubeconfig
          secret:
            defaultMode: 420
            secretName: controlplane-kubeconfig
