apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: grc-metrics-cert
  labels:
    app: grc
    app.kubernetes.io/instance: grc
    app.kubernetes.io/name: grc
    chart: grc-chart-2.7.0
    component: ocm-policy-propagator
    release: grc
  name: grc-policy-propagator-metrics
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: grc
    component: ocm-policy-propagator
    release: grc
  sessionAffinity: None
  type: ClusterIP
