apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:policy-controller:addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:policy-controller:addon-manager
subjects:
- kind: ServiceAccount
  name: policy-sa
