apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:hub:escalation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:hub:escalation
subjects:
  - kind: ServiceAccount
    name: hub-sa
    namespace: open-cluster-management-hub
