# RoleBinding for registration mandatory permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management:registration-agent
  namespace: open-cluster-management-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management:registration-agent
subjects:
  - kind: ServiceAccount
    name: spoke-agent-sa
    namespace: open-cluster-management-agent
