# Create the cluster rolebinding so klusterlet can deploy others
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:{{ .KlusterletName }}-registration-operator:operator-kube111
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: klusterlet
    namespace: {{ .OperatorNamespace }}
