{{- if or .Values.bootstrapHubKubeConfig .Values.externalManagedKubeConfig }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    workload.openshift.io/allowed: "management"
{{- if or ( eq .Values.klusterlet.mode "Hosted") (eq .Values.klusterlet.mode "HostedSingleton") }}
  name: "klusterlet-{{ .Values.klusterlet.clusterName }}"
{{- else }}
  name: {{ .Values.klusterlet.namespace | default "open-cluster-management-agent" }}
{{- end }}
{{- end }}
