{{- if .Values.externalManagedKubeConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: external-managed-kubeconfig
  {{- if or ( eq .Values.klusterlet.mode "Hosted") (eq .Values.klusterlet.mode "HostedSingleton") }}
  namespace: "klusterlet-{{ .Values.klusterlet.clusterName }}"
  {{- else }}
  namespace: {{ .Values.klusterlet.namespace | default "open-cluster-management-agent" }}
  {{- end }}
type: Opaque
data:
  kubeconfig: {{ .Values.externalManagedKubeConfig | b64enc }}
{{- end }}
