{{- if .Values.externalManagedKubeConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: external-managed-kubeconfig
  namespace: "{{ template "agentNamespace" . }}"
type: Opaque
data:
  kubeconfig: {{ .Values.externalManagedKubeConfig | b64enc }}
{{- end }}
