{{- if or ( eq .Values.klusterlet.mode "Singleton") (eq .Values.klusterlet.mode "Default") }}
{{- if not .Values.noOperator }}
{{- if .Values.priorityClassName }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClassName }}
value: 1000000
globalDefault: false
description: "This priority class should be used for klusterlet agents only."
preemptionPolicy: PreemptLowerPriority
{{- end }}
{{- end }}
{{- end }}
