{{- if not .Values.noOperator }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: klusterlet
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: open-cluster-management-image-pull-credentials
{{- end }}
