apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .WorkServiceAccount }}
  namespace: {{ .KlusterletNamespace }}
  labels:
    {{ if gt (len .Labels) 0 }}
    {{ range $key, $value := .Labels }}
    {{ $key }}: {{ $value }}
    {{ end }}
    {{ end }}
imagePullSecrets:
- name: open-cluster-management-image-pull-credentials
