# ClusterRoleBinding for work execution permissions.
# TODO: replace this with user defined execution permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:{{ .KlusterletName }}-work:execution
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:{{ .KlusterletName }}-work:aggregate
subjects:
  - kind: ServiceAccount
    name: {{ .WorkServiceAccount }}
    namespace: {{ .KlusterletNamespace }}
