apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .RegistrationServiceAccount }}
  namespace: {{ .KlusterletNamespace }}
  labels:
    {{ if gt (len .Labels) 0 }}
    {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
    {{ end }}
    {{ end }}
  {{ if and .ManagedClusterRoleArn (eq .RegistrationDriver.AuthType "awsirsa") }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .ManagedClusterRoleArn }}
  {{ end }}
imagePullSecrets:
- name: open-cluster-management-image-pull-credentials
