apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
- rbac/cluster_role.yaml
- rbac/cluster_role_binding.yaml
- operator/namespace.yaml
- operator/service_account.yaml
- operator/operator.yaml

generatorOptions:
  disableNameSuffixHash: true

replicas:
- count: 1
  name: klusterlet

images:
- name: quay.io/open-cluster-management/registration-operator:latest
  newName: quay.io/open-cluster-management/registration-operator
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/imagePullPolicy"
      value: IfNotPresent
  target:
    kind: Deployment
