name: Deploy to release hotfix
jobs:
  deploy_to_release:
    uses: Groww/github-wf-templates/.github/workflows/deploy_hotfix.yaml@master
    with:
      build_version: ${{ github.event.inputs.build_version }}
      env: release
      BUILD_PROFILE: ${{ github.event.inputs.build_profile }}
    secrets: inherit
on:
  workflow_dispatch:
    inputs:
      build_profile:
        description: Select profile to run
        required: true
        default: work
        type: choice
        options:
        - registration
        - work
        - placement
        - registration-operator
        - addon-manager
      build_version:
        description: Build Version
        required: true
      additional_comments:
        description: Comments
        required: true