apiVersion: v1
kind: ServiceAccount
metadata:
  name: work-webhook-sa
  namespace: {{ .ClusterManagerNamespace }} 
  labels:
    {{ if gt (len .Labels) 0 }}
    {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
    {{ end }}
    {{ end }}
