apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: managedclustermutators.admission.cluster.open-cluster-management.io
  labels:
    {{ if gt (len .Labels) 0 }}
    {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
    {{ end }}
    {{ end }}
webhooks:
- name: managedclustermutators.admission.cluster.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: {{ .ClusterManagerNamespace }}
      name: cluster-manager-registration-webhook
      path: /mutate-cluster-open-cluster-management-io-v1-managedcluster
      port: {{.RegistrationWebhook.Port}}
    caBundle: {{ .RegistrationAPIServiceCABundle }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - cluster.open-cluster-management.io
    apiVersions:
    - "*"
    resources:
    - managedclusters
  admissionReviewVersions: ["v1beta1","v1"]
  sideEffects: None
  timeoutSeconds: 10
