apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-registration-webhook
  namespace: {{ .ClusterManagerNamespace }}
  labels:
    {{ if gt (len .Labels) 0 }}
    {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
    {{ end }}
    {{ end }}
spec:
  selector:
    app: {{ .ClusterManagerName }}-registration-webhook
  ports:
  - name: webhook
    port: {{ .RegistrationWebhook.Port }}
    targetPort: {{ .RegistrationWebhook.Port }}
