apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: manifestworkvalidators.admission.work.open-cluster-management.io
  labels:
    {{ if gt (len .Labels) 0 }}
    {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
    {{ end }}
    {{ end }}

webhooks:
- name: manifestworkvalidators.admission.work.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: {{ .ClusterManagerNamespace }}
      name: cluster-manager-work-webhook
      path: /validate-work-open-cluster-management-io-v1-manifestwork
      port: {{.WorkWebhook.Port}}
    caBundle: {{ .WorkAPIServiceCABundle }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - work.open-cluster-management.io
    apiVersions:
    - "*"
    resources:
    - manifestworks
  admissionReviewVersions: ["v1beta1","v1"]
  sideEffects: None
  timeoutSeconds: 10