kind: Endpoints
apiVersion: v1
metadata:
  name: cluster-manager-work-webhook
  namespace: {{ .ClusterManagerNamespace }}
  labels:
    {{ if gt (len .Labels) 0 }}
    {{ range $key, $value := .Labels }}
    "{{ $key }}": "{{ $value }}"
    {{ end }}
    {{ end }}
subsets:
  - addresses:
      - ip: {{.WorkWebhook.Address}}
    ports:
      - port: {{.WorkWebhook.Port}}
        name: tls
