apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
 name: work-manager
spec:
  addOnMeta:
    displayName: work-manager
    description: "work-manager provides action, view and rbac settings"
  supportedConfigs:
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
